### ISSUE TITLE
App store thinks Xcode command line tools are out of date

### ISSUE THREAD

**Issue by knightsc** [ANTS-Framework/ants#18] opened 2018-07-19 19:00 UTC
I'm using ANTs and Munki. I have a test 10.13.6 machine that I'm testing enrolling in my MDM. The MDM installs Munki and then Munki installs ANTs. The ANTs installer will install the Xcode command line tools so that it can use git. After the install is finished if I go back to Munki or the App Store the machine thinks it needs to update the version of the Command Line Tools installed.

I don't know if this is specifically an issue with ANTs but maybe with the package install script that installs the command line tools. I think I've had this happen on a clean machine after installing homebrew as well which does something similar to download command line tools.

Creating this issue to look into it further. As a starting point I'm planning to check the command line tools version after the ANTS package install. Then after my playbook run and finally after updating what Munki wants me to.

**Comment by aschwanb** [comment] 2018-07-23 15:07
Thanks for opening this issue. I tested with our code and the original script [here](https://github.com/rtrouton/rtrouton_scripts/blob/master/rtrouton_scripts/install_xcode_command_line_tools/install_xcode_command_line_tools.sh): executing the script and running `softwareupdate -l` right afterwards. I could reproduce the behaviour you're describing.

It looks to me like this is an issue with `softwareupdate` and/or the way we install the Xcode command line tools. Either way, I think we have to live with this behaviour as long as we use the git provided by Xcode.

With this being said, it might be worthwhile looking into patching the `ANTS` command line tool to allow the use the [official git client](https://git-scm.com/) which installs in `/usr/local/bin/git`.

**Comment by aschwanb** [comment] 2018-07-26 13:59
Closing this now as it is not an issue with `ANTS` but with Apple `softwareupdate`.

**Closed by aschwanb** 2018-07-26 13:59 UTC

**Comment by aschwanb** [comment] 2018-07-26 15:06
@knightsc I'm adding the results of your debugging to the issue for posterity:
```bash
LOXCLE134C3HTD9:Desktop scottknight$ touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
LOXCLE134C3HTD9:Desktop scottknight$ softwareupdate -l 
Software Update Tool

Finding available software
Software Update found the following new or updated software:
   * Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2
    Command Line Tools (macOS El Capitan version 10.11) for Xcode (8.2), 150374K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.3
    Command Line Tools (macOS High Sierra version 10.13) for Xcode (9.3), 187312K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4
    Command Line Tools (macOS High Sierra version 10.13) for Xcode (9.4), 187380K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4
    Command Line Tools (macOS High Sierra version 10.13) for Xcode (9.4), 187364K [recommended]
```

Our script will then correctly select the name of the newest version of `Command Line Tools`, which is `Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4`. This is the same name as the second to last version.

Hence, `softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4"` will install the second to last version and `softwareupdate` will then - correctly - prompt for an update for `Command Line Tools`.

This naming problem is the reason why we haven’t seen this behaviour earlier. Also, it will disappear again on the next release of `Command Line Tools`.
